### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by SmartMapple** [yfiua/example-jena-dbpedia#1]
why i cannot run this project

[ERROR.txt](https://github.com/yfiua/example-jena-dbpedia/files/3872701/ERROR.txt)

**Comment by yfiua** [comment]
I also have the same issue with SLF4J, but this does not really matter. What SLF4J does is logging, which is not crucial.

What is crucial is the HttpException you got, which may be caused by no connection to DBpedia.
